policy_path: "/home/blake/gen_mimic/logs/rsl_rl/g1_flat/2026-02-05_19-38-30_catch_step_test/2026-02-05_19-38-30_catch_step_test.onnx"
use_gpu: True
plot_feet: False

# Motion trajectory file (npz format from csv_to_npz.py)
# For single motion, use motion_npz_path:
# motion_npz_path: "/home/blake/gen_mimic/artifacts/catch_no_waist_2:v0/motion.npz"
# For multiple motions, use motion_npz_paths (list):
motion_npz_paths:
    - "/home/blake/gen_mimic/artifacts/catch_right_step_1:v0/motion.npz"
    - "/home/blake/gen_mimic/artifacts/catch_left_step_1:v0/motion.npz"
  # - "/home/blake/gen_mimic/artifacts/catch_no_waist_2:v0/motion.npz"
  # - "/home/blake/gen_mimic/artifacts/throw_2:v0/motion.npz"
  # Add more motion files here for multi-motion support

# xml_path: "/home/blake/gen_mimic/g1/scene_29dof_rl.xml"
xml_path: "/home/blake/gen_mimic/g1/scene_29dof_rl.xml"
robot_xml_path: "/home/blake/gen_mimic/g1/g1_29dof_rl.xml"
urdf_path: "/home/blake/gen_mimic/source/whole_body_tracking/whole_body_tracking/assets/unitree_description/urdf/g1/main.urdf"

# Total simulation time
simulation_duration: 50.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * control_decimation=0.02 for 50Hz)
control_decimation: 10
control_dt: 0.02
cmd_scale: [1.0, 1.0, 1.0]
cmd_init: [0.0, 0.0, 0.0]
max_cmd: [0.6, 0.6, 0.3]
# Real stuff
lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"
msg_type: "hg" # "hg" or "go"
imu_type: "pelvis" # "torso" or "pelvis"
weak_motor: False
# Hand control
auto_hand_enabled: True
auto_hand_open: True  # True: open, False: close
auto_hand_frame: 117